# Generated by Django 3.1.13 on 2021-12-23 16:48

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownlayerImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('image', models.ImageField(help_text='a wallpaper is needed to be uploaded , and it the main bannner wallpaper.. note ... keep in mind the size of the image becuase it needs to be saved before image compressing by the app .', max_length=255, null=True, upload_to='', verbose_name='Ad Image')),
                ('redirect_url', models.URLField(blank=True, help_text='this specify the redirect url of the banner image', null=True, verbose_name='Redirect URL')),
                ('status', models.BooleanField(default=False, help_text='the status of the current banner, which determain if the it should be active or not.', null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Down Layer Image',
                'verbose_name_plural': 'Down Layer Image',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='FirstLayerImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('image', models.ImageField(help_text='a wallpaper is needed to be uploaded , and it the main bannner wallpaper.. note ... keep in mind the size of the image becuase it needs to be saved before image compressing by the app .', max_length=255, null=True, upload_to='', verbose_name='Ad Image')),
                ('redirect_url', models.URLField(blank=True, help_text='this specify the redirect url of the banner image', null=True, verbose_name='Redirect URL')),
                ('status', models.BooleanField(default=False, help_text='the status of the current banner, which determain if the it should be active or not.', null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'First Layer Ad Image',
                'verbose_name_plural': 'First Layer Ad Image',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('image', models.ImageField(help_text='a wallpaper is needed to be uploaded , and it the main bannner wallpaper.. note ... keep in mind the size of the image becuase it needs to be saved before image compressing by the app .', max_length=255, null=True, upload_to='', verbose_name='Wallpaper')),
                ('content', models.CharField(help_text='content that will be dsiplayed on the banner image', max_length=500, null=True, verbose_name='Content')),
                ('redirect_url', models.URLField(blank=True, help_text='this specify the redirect url of the banner image', null=True, verbose_name='Redirect URL')),
                ('status', models.BooleanField(default=False, help_text='the status of the current banner, which determain if the it should be active or not.', null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Image',
                'ordering': ('-created_date',),
            },
        ),
    ]
