# Generated by Django 3.1.13 on 2022-01-24 14:57

from django.db import migrations, models
import django.utils.timezone
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20211223_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('description', tinymce.models.HTMLField(help_text='Product description for the current product and note it should be well organized and explainable.', null=True, verbose_name='Product Description')),
                ('active', models.BooleanField(default=False, null=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'About Us Content',
                'verbose_name_plural': 'About Us Content',
                'ordering': ('-created_date',),
            },
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='desktop_image',
            field=models.ImageField(help_text='a wallpaper is needed to be uploaded , and it the main bannner wallpaper.. note ... keep in mind the size of the image becuase it needs to be saved before image compressing by the app .', null=True, upload_to='', verbose_name='DeskTop Wallpaper'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='mobile_image',
            field=models.ImageField(help_text='a wallpaper is needed to be uploaded , and it the main bannner wallpaper.. note ... keep in mind the size of the image becuase it needs to be saved before image compressing by the app .', null=True, upload_to='', verbose_name='Mobile Wallpaper'),
        ),
    ]
