# Generated by Django 3.1.13 on 2022-01-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_auto_20220124_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='description',
            new_name='content',
        ),
    ]
