# Generated by Django 3.1.13 on 2021-12-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ('-created_date',), 'verbose_name': 'My Wishlist', 'verbose_name_plural': 'My Wishlist'},
        ),
    ]
