# Generated by Django 3.1.13 on 2021-10-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(help_text='Product name should be added which identify each product', max_length=500, null=True, verbose_name='Product Name'),
        ),
    ]
