# Generated by Django 3.1.13 on 2021-10-21 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211008_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('variations_category', models.CharField(choices=[('Color', 'Color'), ('Size', 'Size')], help_text='Select which variation category to the current product', max_length=255, verbose_name='Variations')),
                ('variation_value', models.CharField(help_text='the value to select for the variation product', max_length=250, null=True, verbose_name='Variation Value')),
                ('is_active', models.BooleanField(default=True, help_text='Status to dectect if the product variation is active or not', null=True, verbose_name='Variation Status')),
                ('product', models.ForeignKey(help_text='Product name refering to the product already uplaoded and to be added some variatons.', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Product Variation ',
                'verbose_name_plural': 'Product Variation',
                'ordering': ('-created_date',),
            },
        ),
    ]
