# Generated by Django 3.1.13 on 2021-10-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productvariantmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariantManager',
        ),
    ]
