# Generated by Django 3.1.13 on 2021-10-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_productvariantmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='variations_category2',
            field=models.CharField(choices=[('Color', 'Color'), ('Size', 'Size')], help_text='Select which variation category to the current product', max_length=255, null=True, verbose_name='Variations'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='variations_category',
            field=models.CharField(choices=[('Color', 'Color'), ('Size', 'Size')], help_text='Select which variation category to the current product', max_length=255, null=True, verbose_name='Variations'),
        ),
    ]
