# Generated by Django 3.1.13 on 2021-10-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211021_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='variations_category2',
        ),
    ]
