# Generated by Django 3.1.13 on 2021-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211027_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, help_text='Product old price for the current product', null=True, verbose_name='Product Old Price'),
        ),
    ]
