# Generated by Django 3.1.13 on 2021-10-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sku',
            field=models.CharField(help_text='Product sku should be added which identify each product', max_length=500, null=True, verbose_name='Product SKU'),
        ),
    ]
