# Generated by Django 3.1.13 on 2021-11-02 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_product_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('review', models.TextField(help_text='customer review the customer item.', max_length=500, null=True, verbose_name='Product Review')),
                ('rating', models.FloatField(null=True, verbose_name='Product Rating')),
                ('status', models.BooleanField(default=True, help_text='Status to dectect if the product review is active or not', null=True, verbose_name='Status')),
                ('product', models.ForeignKey(help_text='Product which the rating will be published to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Product Name')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Product Review ',
                'verbose_name_plural': 'Product Review',
                'ordering': ('-created_date',),
            },
        ),
    ]
