# Generated by Django 3.1.13 on 2021-11-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_reviewrating_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Product Rating'),
        ),
    ]
