# Generated by Django 3.1.13 on 2021-11-09 00:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20211106_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(help_text='Product description for the current product and note it should be well organized and explainable.', null=True, verbose_name='Product Description'),
        ),
    ]
