# Generated by Django 3.1.13 on 2021-11-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20211109_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(help_text='Short description of the product which shouldnt be long.', max_length=255, null=True, verbose_name='Product Short Description'),
        ),
    ]
