# Generated by Django 3.1.13 on 2021-10-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_productvariation_variations_category2'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_variation',
            field=models.ManyToManyField(null=True, to='store.ProductVariation'),
        ),
    ]
