# Generated by Django 3.1.13 on 2021-09-30 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import next.users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'All Registered Customer', 'verbose_name_plural': 'All Registered Customer'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', next.users.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(help_text='The last nammes of the investor.', max_length=50, null=True, verbose_name='Last names'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_currency_id',
            field=models.CharField(blank=True, default='USD', help_text='The default currency of the investor. Currency will be sent against Customer country of residence.', max_length=3, null=True, verbose_name='Default Currency ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='The first nammes of the investor.', max_length=50, null=True, verbose_name='First names'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='The last nammes of the investor.', max_length=50, null=True, verbose_name='Last names'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='The email address of the investor.', max_length=150, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the investor.', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('hostname', models.CharField(blank=True, help_text='The Host Name of the logged in user system', max_length=355, null=True, verbose_name='Host Name')),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, help_text=' The system IP address to current login user', null=True, verbose_name='System IP Address')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'All Users Activity',
                'verbose_name_plural': 'All Users Activity',
                'ordering': ('-created_date',),
            },
        ),
    ]
