# Generated by Django 3.1.13 on 2021-10-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_currency_id',
            field=models.CharField(blank=True, default='NGN', help_text='The default currency of the investor. Currency will be sent against Customer country of residence.', max_length=3, null=True, verbose_name='Default Currency ID'),
        ),
    ]
