# Generated by Django 3.1.13 on 2021-10-26 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userregisteredip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregisteredip',
            options={'verbose_name': 'Base Model', 'verbose_name_plural': 'Base Model'},
        ),
        migrations.RemoveField(
            model_name='userregisteredip',
            name='registered_ip_address',
        ),
        migrations.RemoveField(
            model_name='userregisteredip',
            name='user',
        ),
    ]
