# Generated by Django 3.1.13 on 2021-10-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211026_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisteredip',
            name='is_active',
            field=models.BooleanField(default=False, help_text='The user ip address status which is to be set for accepting user ip address ', null=True, verbose_name='IP Address Status'),
        ),
    ]
