# Generated by Django 3.1.13 on 2021-11-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_address',
            name='default',
            field=models.BooleanField(default=False, help_text='to identify which shipping address is the default shipping address.', null=True, verbose_name='Default Shipping Address'),
        ),
    ]
