# Generated by Django 3.1.13 on 2021-11-29 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_shipping_address_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(help_text='contact number of the customer.', max_length=50, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_currency_id',
            field=models.CharField(blank=True, default='NGN', help_text='The default currency of the customer. Currency will be sent against Customer country of residence.', max_length=3, null=True, verbose_name='Default Currency ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='The email address of the customer.', max_length=150, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='The first nammes of the customer.', max_length=50, null=True, verbose_name='First names'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the customer.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='The last nammes of the customer.', max_length=50, null=True, verbose_name='Last names'),
        ),
    ]
