# Generated by Django 3.1.13 on 2021-10-06 13:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Specify the category name.', max_length=80, null=True, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, help_text='Slug field for the category which is auto generated when the category is been created', max_length=300, null=True, verbose_name='Category Slug')),
                ('image', models.ImageField(blank=True, help_text='category image is meant to be png JPG JPEG', null=True, upload_to='categories_image/', verbose_name='Category Image')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Parent category refers to the main parent of the child category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='Category Parent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
