# Generated by Django 3.1.13 on 2021-10-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Add or Delete Category', 'verbose_name_plural': 'Add or Delete Category'},
        ),
    ]
