# Generated by Django 3.1.13 on 2021-12-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20211008_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(help_text='category image is meant to be png JPG JPEG', null=True, upload_to='categories_image/', verbose_name='Category Image'),
        ),
    ]
