# Generated by Django 3.1.13 on 2021-12-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20211203_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='category image is meant to be png JPG JPEG', null=True, upload_to='categories_image/', verbose_name='Category Image'),
        ),
    ]
