# Generated by Django 3.1.13 on 2021-10-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Customers address line 2 ', max_length=400, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True, help_text='A short note for the order to be delieved to you.', null=True, verbose_name='Order Note'),
        ),
    ]
