# Generated by Django 3.1.13 on 2021-11-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211031_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(help_text='City of which the order is been placed from or to be shipped to.', max_length=400, null=True, verbose_name='Order City'),
        ),
    ]
