# Generated by Django 3.1.13 on 2021-11-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_rate_per_quantity',
            field=models.IntegerField(blank=True, help_text='Shipping rate for the current order placed by the customer', null=True, verbose_name='Order Shipping Rate'),
        ),
    ]
