# Generated by Django 3.1.13 on 2021-11-01 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_order_shipping_rate_per_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('payment_id', models.CharField(help_text='The payment identification number sent from the payment gateway.', max_length=150, null=True, verbose_name='Payment ID')),
                ('payment_method', models.CharField(help_text='The payment method used while paying for an order.', max_length=150, null=True, verbose_name='Payment Method')),
                ('amount_paid', models.CharField(help_text='Amount paid for the above order by the customer.', max_length=150, null=True, verbose_name='Amount Paid')),
                ('status', models.CharField(help_text='Verified payment status to identify if the payment is been verified by the payment gateway or not.', max_length=150, null=True, verbose_name='Payment Status')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'All Payment',
                'verbose_name_plural': 'All Payment',
                'ordering': ('-created_date',),
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Customers order payment information.', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.payment'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='foreign key and session to the payment table.', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.payment'),
        ),
        migrations.DeleteModel(
            name='Payement',
        ),
    ]
