# Generated by Django 3.1.13 on 2021-11-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211101_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='Online Payment', help_text='The payment method used while paying for an order.', max_length=150, null=True, verbose_name='Payment Method'),
        ),
    ]
