# Generated by Django 3.1.13 on 2021-11-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20211101_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_ref',
            field=models.CharField(help_text='The payment identification number sent from the payment gateway.', max_length=150, null=True, verbose_name='Payment Ref No'),
        ),
    ]
