# Generated by Django 3.1.13 on 2021-11-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20211101_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(help_text='payment status to identify if the payment is been verified by the payment gateway or not.', max_length=150, null=True, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verified',
            field=models.BooleanField(default=False, help_text='Verified payment status to identify if the payment is been verified by the payment gateway or not.', null=True, verbose_name='Payment Verification'),
        ),
    ]
