# Generated by Django 3.1.13 on 2021-11-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20211101_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='verified',
            field=models.BooleanField(blank=True, default=False, help_text='Verified payment status to identify if the payment is been verified by the payment gateway or not.', null=True, verbose_name='Payment Verification'),
        ),
    ]
