# Generated by Django 3.1.13 on 2021-11-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_reviewrating'),
        ('orders', '0013_auto_20211102_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='variation',
            field=models.ManyToManyField(blank=True, help_text='foreign key and session to the product variation table.', to='store.ProductVariation'),
        ),
    ]
